### ISSUE TITLE
Openid-configuration request blocked by CORS policy 

### ISSUE THREAD

**Issue by mh-ckantzer** [okta/okta-auth-js#679]
Hello,
We recently starting seeing an issue in the console with our Okta integration on Chrome browsers. Newer version of Edge do not have this issue.  The issue still occurs even if we clear the cache/cookies from the browser session.

'Access to XMLHttpRequest at ‘https://mycompany.okta.com/.well-known/openid-configuration’ from origin ‘mycompany.com’ has been blocked by CORS policy: No ‘Access-Control-Allow-Origin’ header is present on the requested resource.

We’ve verified that the CORS policy is set correctly in Okta for our client domain. We know this is an issue with Chrome, but we’d like to avoid switching or updating our users browsers.

I’ve tried setting the issuer field in the Okta auth component, but we still are getting the error. I tried both 2.13.0 and 3.2.5 in our legacy Angular app. We are using the .getWithoutPrompt method on OktaAuth.

We are not seeing the CORS error on other Okta calls (authorize, etc). Is there a way to fix this or disable the call to openid-configuration for our flow?

Thanks,
Chris

**Comment by bryanapellanes-okta** [comment]
@mh-ckantzer,
Thanks for reaching out!   I've gone ahead and added an item to the backlog for further review and prioritization.  Our JavaScript developers will follow up after reviewing more closely.

Thanks for using Okta!

**Comment by luckyluckytina** [comment]
@mh-ckantzer  As discussed in the meeting today, the chrome incognito window works. We doubt the issue is caused by Okta browser plugin. I've added test steps for you via ticket. Please send me a test result once you done. That will be very helpful to confirm the root cause.
@bryanapellanes-okta

**Comment by Karkunow** [comment]
@luckyluckytina @bryanapellanes-okta I have the same trouble on my project. Incognito tab indeed works fine. But removing cookies doesn't solve the issue for Chrome. Please advice something to mitigate the problem.

**Comment by OliverLeighC** [comment]
We are having this same issue but with the /oauth/v1/keys endpoint, it was working fine on Friday and we haven't changed any configurations. It works in incognito, but in regular chrome it throws a CORS error

**Comment by cracell** [comment]
I have 3 users hitting this issue and incognito works from them as well.


I found I'm able to reproduce it by misconfiguring my issuer and attempting to login.
Then fixing it but find that I still get the CORS error. 
![Screen Shot 2021-04-05 at 1 30 19 PM](https://user-images.githubusercontent.com/8106/113640482-5f83c580-9630-11eb-8130-2e825bc031fc.png)

Once in this state Chrome has cached the failed request and just keeps grabbing that cache.

If you then run this in console
```
xmlhttp = new XMLHttpRequest();
xmlhttp.open("GET", "https://westernmilling.okta.com/.well-known/openid-configuration", true);
xmlhttp.setRequestHeader('Access-Control-Allow-Origin', '*');
xmlhttp.send();
```

Same error but the request is not actually sent.

But if you run
```
xmlhttp = new XMLHttpRequest();
xmlhttp.open("GET", "https://westernmilling.okta.com/.well-known/openid-configuration", true);
xmlhttp.setRequestHeader('Access-Control-Allow-Origin', '*');
xmlhttp.setRequestHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
xmlhttp.send();
```

It works and actual apps requests start working again too.

I believe this is because the `getWellKnown` request response is cached regardless if it succeeds or not.

https://github.com/okta/okta-auth-js/blob/6d16f8f98665d9d1034afe3aa14dbf2af24c3978/lib/oidc/endpoints/well-known.ts#L21

So if a request to it does have an issue, then you get in a stuck state due to the cache.

**Comment by luckyluckytina** [comment]
@Karkunow @OliverLeighC @cracell We already had an internal JIRA for this issue. ENG team is working on it.
Meanwhile, you can check if the below workaround works for you.

If incognito window works, please try to clear cache and cookies in your browser and see if it works.
If the above step does not work, check if you have Okta Browser plugin installed. Try to disable that plugin and clear cookies & cache in the browser and test again.
Do not forget quit and restart chrome after you clear cookies.
Let us know your test results.

**Comment by OliverLeighC** [comment]
@luckyluckytina clearing cookies worked for me (I don't have the okta browser plugin installed).

**Comment by felipethome** [comment]
Clearing cookies does not work for all of our users, but incognito does. @luckyluckytina any updates on this?

**Comment by luckyluckytina** [comment]
@felipethome What is your browser? Did you check if you have browser plugin installed?

**Comment by bmax329** [comment]
Clearing cached images and files (not cookies) works for us (which is why incognito also works). @felipethome you may want to give that a go.

I just confirmed @cracell's solution. Except it appears the request to `oauth2/v1/keys` also fails in our case due to the same cached CORS error. This is our full solution to get around having to clear the cache/incognito:

```javascript
xmlhttp = new XMLHttpRequest();
xmlhttp.open("GET", "https://<domain>.okta.com/.well-known/openid-configuration", true);
xmlhttp.setRequestHeader('Access-Control-Allow-Origin', '*');
xmlhttp.setRequestHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
xmlhttp.send();

xmlhttp = new XMLHttpRequest();
xmlhttp.open("GET", "https://<domain>.okta.com/oauth2/v1/keys", true);
xmlhttp.setRequestHeader('Access-Control-Allow-Origin', '*');
xmlhttp.setRequestHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
xmlhttp.send();

window.location.reload()
```

**Comment by markgillnz** [comment]
@bmax329 does this need to be applied to each users' console or does it fix the issue server-side?

**Comment by markgillnz** [comment]
> @bmax329 does this need to be applied to each users' console or does it fix the issue server-side? We are seeing this issue for our clients in a production system and do not have the luxury of accessing each console....

UPDATE: As per https://devforum.okta.com/t/openid-configuration-request-blocked-by-cors-policy/13607/7 this issue appears to have a fix by Okta

**Comment by arvin-yao** [comment]
Hello,
I have same question:

**Comment by mh-ckantzer** [comment]
Are you able to post the fix here?

**Comment by cdnrg-rt** [comment]
Still having the issue as of this morning. Chrome version 89.0.4389.114 Windows 10 Pro version 2004, OS build 19041.867. Cleared all caches. Most users are fine.

**Comment by aarongranick-okta** [comment]
@mh-ckantzer @cdnrg-rt @markgillnz @bmax329 @felipethome @luckyluckytina @cracell @Karkunow 

We have been able to reproduce this issue and we have found the source of the bug. A fix is pending now and should be pushed to production soon. 

The issue occurs when a "1st party" application (such as your Okta user home page) is using OIDC *and* you have an OIDC app (3rd party, running on a different domain) which is configured to use the "org" authorization server (this is your Okta "org url"). On a clean cache (such as incognito window), if the first request is from the 1st party app, "CORS" headers will not be returned, since the app is running on the same origin.  The second request from the 3rd party app wrongly receives a cached response which does not contain the headers. The fix on our side is to add a cache "vary" header for origin, for all requests to this endpoint.

As a temporary workaround, I can suggest:
- Use the "old" user home page experience, which does not use OIDC, or
- Configure your app to use a "custom" authorization server, such as `https://yourorg.okta.com/oauth2/default`

Either of these workarounds should prevent this bug from being seen.

**Comment by mh-ckantzer** [comment]
Thanks for the update.

For those of us using the OktaAuth SDK how would we apply the 2nd workaround?  Would we update the issuer from https://yourorg.okta.com with https://yourorg.okta.com/oauth2/default?

**Comment by aarongranick-okta** [comment]
@mh-ckantzer 

Yes, exactly right. "default" is the name of the default "custom authorization server". You can create additional servers which can enforce specific policies or provide additional access for your app. 

The "org" authorization server, which cannot be customized directly, is used primarily by applications which need access to certain lower level Okta user apis (such as the enduser home page on Okta)

Here are a couple of links with more information:
https://github.com/okta/okta-auth-js#about-the-issuer
https://developer.okta.com/docs/concepts/auth-servers/

Thanks again for your report which helped us reproduce and identify the source of this (very tricky) bug.

**Comment by felipethome** [comment]
We are seeing a CORs error with `{{company}}.okta.com/oauth2/v1/keys` request for some of our users. Any chance this endpoint may also be suffering from the same issue?

**Comment by cdnrg-rt** [comment]
Any updates on when the fix will be pushed to production? Still having more reports this morning of the CORS issues popping up on Firefox and Chrome.

**Comment by aarongranick-okta** [comment]
@cdnrg-rt the fix was pushed to "preview" last week and my understanding is that it is being pushed out to production today and tomorrow. The client cache time is 24 hours, so I expect the issue to be completely resolved before the end of the week.

**Comment by cjoelrun** [comment]
Our users started experiencing this around the same time. Uninstalling the okta chrome extension fixed the problem. Still seeing it occur in our testing environment with the okta extension installed today.

**Comment by Karkunow** [comment]
@aarongranick-okta I am still experiencing it right now.

**Comment by mh-ckantzer** [comment]
The issue seems to be fixed for our users in Chrome after clearing the cache.  

@aarongranick-okta Should I keep this ticket open for a while longer?

**Comment by Karkunow** [comment]
@mh-ckantzer I've cleared cache and cookies, restarted a browser and yet - no luck.

**Comment by sscho** [comment]
Not sure if this is the same issue, but I just started trying to integrate okta with my React app. After setting things up on my frontend (using Authorization code + PKCE) I've been getting the error message: 

`Access to fetch at '{my_okta_domain}/oauth2/default/.well-known/openid-configuration' from origin '{my_website_url}' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I've added my_website_url into the API > Trusted Origins, but it's still giving me this error. 
This occurs even in Incognito mode, and other browsers (Safari), so I don't think it's a browser issue...

**Comment by askouras** [comment]
@sscho Can you confirm that you can find the Authorization Server called "Default" if in the Okta Admin Console you go to API -> Security -> Authorization Servers?

If you do not see the "Authorization Servers" tab, you are likely missing the required SKU/feature (API Access Management) that creates this "Default" custom authorization server, in which case you will want to set the Issuer in your application to just your Okta domain so you can request tokens from the built-in Org Authorization Server instead (which is available to Orgs even if they do not have the previously mentioned SKU)

**Comment by sscho** [comment]
@askouras Hi, thank you for your prompt response. I fixed the issue! I had to change my config from 

issuer: {my okta org url}default/oauth2

to

issuer: {my okta org url}

Thanks and have a great weekend!

**Comment by aarongranick-okta** [comment]
@Karkunow were you able to resolve your issue, or are you still experiencing problems?

**Comment by Karkunow** [comment]
@aarongranick-okta I had it today. But after I've cleared my cache in Chrome - it disappeared. Not sure if it won't be back in a few days. Because cleaning the cache haven't helped last Friday.

**Comment by dusan-dragon** [comment]
@aaronbrodersen-okta we are also still seeing that error. Can you please confirm that it is deployed to production and we should not be having this issue?

**Comment by OliverLeighC** [comment]
I am also still having this issue, it goes away when I clear my cache and disable the okta browser plugin, but only for a few days. I tried updating chrome as well with no luck.

**Comment by aarongranick-okta** [comment]
The fix for this issue has been deployed and confirmed.
