### ISSUE TITLE
'AuthSdkError: Unable to parse a token from the url' after redirect 

### ISSUE THREAD

**Issue by StanMarian** [okta/okta-auth-js#88]
Hello,

I'm using `@okta/okta-signin-widget/dist/js/okta-sign-in-no-jquery.js` in an Angular SPA.
After I'm logging in and after being redirected to my `redirectUri` (which is `/`) I'm getting this error:
`ERROR Error: Uncaught (in promise): AuthSdkError: Unable to parse a token from the url`.
I'm using the method `handleAuthentication()` from `OktaAuthService` so I've followed the flow and it seems that the problem is at https://github.com/okta/okta-auth-js/blob/ccd7b2e0fd0bb2130290346376f91262f9c40954/lib/token.js#L598
It seems that the `parseFromUrl` method is being called without passing the `url` parameter.
I'm not sure how this should be fixed, hence this issue :)

PS: if I'm doing something wrong please tell me. My widget configuration is minimal: only `baseUrl` is set. Maybe there are more params to set?

Thank you!

**Comment by ssaxena48** [comment]
I am also facing the same issue with AngularJS application(1.5.5).

5.	errorSummary:"Unable to parse a token from the url"
6.	message:"Unable to parse a token from the url"
7.	name:"AuthSdkError"
8.	__proto__:Error at Object.<anonymous> (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:18:23299) at t (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:13:326) at Object.<anonymous> (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:18:23066) at t (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:13:326) at Object.<anonymous> (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:18:21973) at t (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:13:326) at Object.<anonymous> (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:18:21404) at t (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:13:326) at Object.<anonymous> (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:18:19785) at t (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:13:326)
1.	stack:"Error↵    at Object.<anonymous> (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:18:23299)↵    at t (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:13:326)↵    at Object.<anonymous> (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:18:23066)↵    at t (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:13:326)↵    at Object.<anonymous> (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:18:21973)↵    at t (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:13:326)↵    at Object.<anonymous> (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:18:21404)↵    at t (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:13:326)↵    at Object.<anonymous> (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:18:19785)↵    at t (https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.8.0/okta-auth-js.min.js:13:326)"
2.	__proto__:Object


I see the IdToken coming in the URL - 

http://localhost:4200/callback#id_token=<Token Value>

Verified the token also on jwt.io. It all looks good.

**Comment by stlcubsfan** [comment]
I also see ```AuthSdkError: Unable to parse a token from the url```
but for me, the result is always undefined getting the ```okta-oauth-redirect-params``` cookie [here](https://github.com/okta/okta-auth-js/blob/ccd7b2e0fd0bb2130290346376f91262f9c40954/lib/token.js#L602)

**Comment by mraible** [comment]
If you're using Angular 5.2.9, this problem should no longer exist. It exists with Angular 5.2.8.

**Comment by kthomas182** [comment]
I'm running 5.2.11 and I still have the issue of:

`AuthSdkError {name: "AuthSdkError", message: "Unable to parse a token from the url", errorCode: "INTERNAL", errorSummary: "Unable to parse a token from the url", errorLink: "INTERNAL", …}
errorCauses
:
[]
errorCode
:
"INTERNAL"
errorId
:
"INTERNAL"
errorLink
:
"INTERNAL"
errorSummary
:
"Unable to parse a token from the url"
message
:
"Unable to parse a token from the url"
name
:
"AuthSdkError"`

**Comment by jmelberg-okta** [comment]
This was caused by grouping together two error messages. As @stlcubsfan mentioned, if the `okta-oauth-redirect-params` cookie isn't present, we returned that cryptic error message.

This issue has been resolved with [`2.0.0`](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-2.0.0).

**Comment by kcferguson1** [comment]
![okta issue](https://user-images.githubusercontent.com/7386075/46030002-cd3af800-c0a9-11e8-919e-c1ec252c4012.jpg)

**Comment by kcferguson1** [comment]
still getting this issue even after using 2.0.0

![okta issue](https://user-images.githubusercontent.com/7386075/46030048-e93e9980-c0a9-11e8-8074-c6d678278688.jpg)

**Comment by jmelberg-okta** [comment]
@kcferguson1 -

Best guess as to why you're seeing that error is due to the cookie not being set/read when returning from a redirect. Can you confirm that [cookies are enabled](https://www.technipages.com/ie-enable-disable-cookies)?

If they are, please provide us with reproduction steps or a sample app so we can debug further.

**Comment by kcferguson1** [comment]
Solved, this was a browser site trust issue

**Comment by nharrisanalyst** [comment]
@kcferguson1 can you give more explanation on what a 'browser site trust issue is'?

**Comment by nharrisanalyst** [comment]
@jmelberg-okta I am having the same issue and a simple google search shows that this is a common error it would be nice if their was some official documentation on how to fix this as I can seem to find a solution
